<table class="table-bordered table-sm">
  <thead>
    <tr>
        <th colspan="2">
            MAN-tra Retreat Schedule <br/>
            October 5-7 New Vrindavana
        </th>
    </tr>
  </thead>

  <tr>
      <th class="day" colspan="2">Friday, October 5th (Ekadasi)</th>
  </tr>

  <tr>
      <td class="slot">10 AM - 8 PM</td>
      <td class="event">Registration @ Visitors Center</td>
  </tr>
  <tr>
      <td class="slot">1 PM</td>
      <td class="event">Lunch</td>
  </tr>
  <tr>
      <td class="slot">2:30 PM - 3:45 PM</td>
      <td class="event">Opening Session and Welcome!</td>
  </tr>
  <tr>
      <td class="slot">4 PM - 6:15 PM</td>
      <td class="event">Seva & Sanga</td>
  </tr>
  <tr>
      <td class="slot">6:30 PM</td>
      <td class="event">Kirtan Walk with Bhaktimarga Swami to
  Old Vrindavan</td>
  </tr>
  <tr>
      <td class="slot">7:30 PM</td>
      <td class="event">Bonfire & Prasadam at Old Vrindavan</td>
  </tr>
  <tr>
      <td class="slot">9:15 PM</td>
      <td class="event">Torchlight Harinam</td>
  </tr>


    <tr>
     <th class="day" colspan="2">Saturday, October 6th</th>
     </tr>

  <tr>
      <td class="slot">5 AM - 9 AM</td>
      <td class="event">Temple Program</td>
  </tr>
  <tr>
      <td class="slot">5:45 AM - 6:45 AM</td>
      <td class="event">Yoga for Men</td>
  </tr>
  <tr>
      <td class="slot">8 AM</td>
      <td class="event">MAN-tra Retreat Bhagavatam Class</td>
  </tr>
  <tr>
      <td class="slot">9 AM</td>
      <td class="event">Breakfast</td>
  </tr>

  <tr>
      <td class="slot">10 AM -11:30 AM</td>
      <td class="event">Plenary with Professor Burke Rochford: <br/>
        <p class="indent">
          The Role of Men in ISKCON -- <br/>
          Lessons Learned and Questions Raised</td>
        </p>
  </tr>
  <tr>
      <td class="slot">11:30 AM</td>
      <td class="event">Break</td>
  </tr>
  <tr>
      <td class="slot">11:45 AM</td>
      <td class="event">Comedy with Yadunath Dasa</td>
  </tr>
  <tr>
      <td class="slot">12 PM - 1:30 PM</td>
      <td class="event">Panel: Being Yourself in Krishna’s Service</td>
  </tr>
  <tr>
      <td class="slot">1:30 PM</td>
      <td class="event">Lunch</td>
  </tr>
  <tr>
      <td class="slot">2:30 PM - 4 PM</td>
      <td class="event">Workshop Options: <br>
      <p class="indent">
        (A) The Ability in Man: How to Find Your Style! <br/>
        (B) The Matter of Spirit: Harmonizing Worldly & Spiritual Pursuits
      </p>
  </td>
  </tr>
  <tr>
      <td class="slot">4 PM - 5:45 PM</td>
      <td class="event">Sports & Sanga</td>
  </tr>
  <tr>
      <td class="slot">6 PM - 7 PM</td>
      <td class="event">Dinner</td>
  </tr>
  <tr>
      <td class="slot">7 PM </td>
      <td class="event">Arati</td>
  </tr>
  <tr>
      <td class="slot">7:30 PM - 9:30 PM</td>
      <td class="event">Drama with Bhaktimarga Swami<br/>
          Comedy with Yadunatha<br/>
          Kirtan with Gaura Vani & Friends
      </td>
  </tr>

  <tr>
      <th class="day" colspan="2">
          Sunday, October 7th
      </th>>
  </tr>

  <tr>
      <td class="slot">5 AM - 9 AM </td>
      <td class="event">Temple Program</td>
  </tr>
  <tr>
      <td class="slot">5:45 AM - 6:45 AM</td>
      <td class="event">Yoga for Men</td>
  </tr>
  <tr>
      <td class="slot">8 AM</td>
      <td class="event">MAN-tra Retreat Bhagavatam Class</td>
  </tr>
  <tr>
      <td class="slot">9 AM</td>
      <td class="event">Breakfast</td>
  </tr>
  <tr>
      <td class="slot">10 AM - 11:30 AM</td>
      <td class="event">Plenary: Navigating The Male Female Paradox</td>
  </tr>
  <tr>
      <td class="slot">11:30   AM</td>
      <td class="event">MAN-tra Group Photo</td>
  </tr>
  <tr>
      <td class="slot">12:00 PM - 1:30 PM</td>
      <td class="event">Plenary: Grow Stronger Through Challenges --
          The Kurukshetra in Our Lives
      </td>
  </tr>
  <tr>
      <td class="slot">1:30 PM - 2:15 PM</td>
      <td class="event">MAN-tra Retreat: Moving Forward</td>
  </tr>
  <tr>
      <td class="slot">2:15 PM</td>
      <td class="event">MAN-tra Sunday Feast</td>
  </tr>
  <tr>
      <td class="slot">3 PM  </td>
      <td class="event">Departure</td>
  </tr>

</table>
