<table>
    <tr>
        <th colspan="2">
            MAN-tra Retreat Schedule<br/>
            October 5-7 New Vrindavana
        </th>
    </tr>
    <tr>
        <th colspan="2">Friday, October 5th (Ekadasi)</th>
    </tr>
    <tr>
        <td>10 AM - 8 PM</td>
        <td>Registration @ Visitors Center</td>
    </tr>
    <tr>
        <td>1 PM</td>
        <td>Lunch</td>
    </tr>
    <tr>
        <td>2:30 PM - 3:45 PM</td>
        <td>Opening Session and Welcome!</td>
    </tr>
    <tr>
        <td>4 PM - 6:15 PM</td>
        <td>Seva & Sanga</td>
    </tr>
    <tr>
        <td>6:30 PM</td>
        <td>Kirtan Walk with Bhaktimarga Swami to
    Old Vrindavan</td>
    </tr>
    <tr>
        <td>7:30 PM</td>
        <td>Bonfire & Prasadam at Old Vrindavan</td>
    </tr>
    <tr>
        <td>9:15 PM</td>
        <td>Torchlight Harinam</td>
    </tr>

   <tr>
       <th colspan="2">Saturday, October 6th</th>
   </tr>

    <tr>
        <td>5 AM - 9 AM</td>
        <td>Temple Program</td>
    </tr>
    <tr>
        <td>5:45 AM - 6:45 AM</td>
        <td>Yoga for Men</td>
    </tr>
    <tr>
        <td>8 AM</td>
        <td>MAN-tra Retreat Bhagavatam Class</td>
    </tr>
    <tr>
        <td>9 AM</td>
        <td>Breakfast</td>
    </tr>

    <tr>
        <td>10 AM -11:30 AM</td>
        <td>Plenary with Professor Burke Rochford: The Role
    of Men in ISKCON -- Lessons Learned and Questions Raised</td>
    </tr>
    <tr>
        <td>11:30 AM</td>
        <td>Break</td>
    </tr>
    <tr>
        <td>11:45 AM</td>
        <td>Comedy with Yadunath Dasa</td>
    </tr>
    <tr>
        <td>12 PM - 1:30 PM</td>
        <td>Panel: Being Yourself in Krishna’s Service</td>
    </tr>
    <tr>
        <td>1:30 PM</td>
        <td>Lunch</td>
    </tr>
    <tr>
        <td>2:30 PM - 4 PM</td>
        <td>Workshop Options: <br>
        <p> (A) The Ability in Man: How to Find Your Style! </p>
        <p> (B) The Matter of Spirit: Harmonizing Worldly & Spiritual Pursuits </p>
    </td>
    </tr>
    <tr>
        <td>4 PM - 5:45 PM</td>
        <td>Sports & Sanga</td>
    </tr>
    <tr>
        <td>6 PM - 7 PM</td>
        <td>Dinner</td>
    </tr>
    <tr>
        <td>7 PM </td>
        <td>Arati</td>
    </tr>
    <tr>
        <td>7:30 PM - 9:30 PM</td>
        <td>Drama with Bhaktimarga Swami<br/>
            Comedy with Yadunatha<br/>
            Kirtan with Gaura Vani & Friends
        </td>
    </tr>

    <tr>
        <th colspan="2">
            Sunday, October 7th
        </th>>
    </tr>

    <tr>
        <td>5 AM - 9 AM </td>
        <td>Temple Program</td>
    </tr>
    <tr>
        <td>5:45 AM - 6:45 AM</td>
        <td>Yoga for Men</td>
    </tr>
    <tr>
        <td>8 AM</td>
        <td>MAN-tra Retreat Bhagavatam Class</td>
    </tr>
    <tr>
        <td>9 AM</td>
        <td>Breakfast</td>
    </tr>
    <tr>
        <td>10 AM - 11:30 AM</td>
        <td>Plenary: Navigating The Male Female Paradox</td>
    </tr>
    <tr>
        <td>11:30   AM</td>
        <td>MAN-tra Group Photo</td>
    </tr>
    <tr>
        <td>12:00 PM - 1:30 PM</td>
        <td>Plenary: Grow Stronger Through Challenges --
            The Kurukshetra in Our Lives
        </td>
    </tr>
    <tr>
        <td>1:30 PM - 2:15 PM</td>
        <td>MAN-tra Retreat: Moving Forward</td>
    </tr>
    <tr>
        <td>2:15 PM</td>
        <td>MAN-tra Sunday Feast</td>
    </tr>
    <tr>
        <td>3 PM  </td>
        <td>Departure</td>
    </tr>

</table>
